#!/usr/bin/python3
from sys import argv
div = 0
if len(argv) != 2:
   raise IndexError("Arguments must be 2")
file = open(argv[1], 'r')
lines = file.readlines()
for number in lines:
    c = int(number)
    if(c % 2 == 0):
        div = c // 2
        print("{:d}={:d}*2".format(c, div))
    else:
        for i in range(3, (c + 1) // 2, 2):
            if(c % i == 0):
                div = c // i
                print("{:d}={:d}*{:d}".format(c, div, i))
                break
